---
- name: install libselinux-python if this is a RedHat derived host OS and selinux is enabled
  yum:
    name={{ item }}
    state=present
  with_items: percona_mysql_selinux_pkgs
  when: ansible_os_family == 'RedHat' and ansible_selinux.status == 'enabled'

- name: Fail if TokuDB and Galera options are enabled
  fail: msg='TokuDB isn''t currently supported on Galera based hosts'
  when: percona_mysql_include_tokudb_variables and percona_mysql_include_galera_variables

- name: change flavor to XtraDB Cluster if Galera install enabled
  set_fact: percona_mysql_pkg_flavor="XtraDB-Cluster"
  when: percona_mysql_include_galera_variables and {{ percona_mysql_server_version|replace(".","")|int }} >= 55

- name: change type to TokuDB if TokuDB install enabled
  set_fact: percona_mysql_pkg_type="tokudb"
  when: percona_mysql_include_tokudb_variables and {{ percona_mysql_server_version|replace(".","")|int }} >= 56

- name: check whether Transparent HugePages are enabled
  shell: 'cat /sys/kernel/mm/transparent_hugepage/enabled | grep -Po "\[\K[^\]]*"'
  changed_when: false
  ignore_errors: yes
  register: percona_mysql_transparent_hugepages
  when: percona_mysql_include_tokudb_variables
  tags: percona_mysql_tokudb_prereq

- name: Disable Transparent HugePages if installing TokuDB
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled
  when: percona_mysql_include_tokudb_variables and percona_mysql_transparent_hugepages.stdout == 'always'
  tags: percona_mysql_tokudb_prereq

- name: add mysql group if it doesn't exist
  group:
    name=mysql
    system=yes
    state=present

- name: add mysql user if it doesn't exist
  user:
    name=mysql
    system=yes
    group=mysql
    comment="MySQL Server"
    home=/dev/null
    shell={{ percona_mysql_user_shell }}
    state=present

- name: create and manage percona_mysql_cnf_dir directory
  file:
    path=/etc/mysql
    owner=mysql
    group=mysql
    mode=0750
    seuser=system_u
    serole=object_r
    setype=mysqld_etc_t
    selevel=s0
    state=directory

- name: create and manage percona_mysql_cnf_dir conf directory
  file:
    path=/etc/mysql/conf.d
    owner=mysql
    group=mysql
    mode=0750
    seuser=system_u
    serole=object_r
    setype=mysqld_etc_t
    selevel=s0
    state=directory

- name: create and manage percona_mysql_run_dir directory
  file:
    path=/var/run/mysqld
    owner=mysql
    group=mysql
    mode=0755
    seuser=system_u
    serole=object_r
    setype=mysqld_var_run_t
    selevel=s0
    state=directory

- name: create and mysql directories and files
  include: configuration_mysql_dir.yml

- name: check if mysql is listening on the percona_mysql_port
  wait_for:
    port={{ percona_mysql_port.value }}
    timeout=1
    state=started
  changed_when: false
  ignore_errors: yes
  register: percona_mysql_port_check
  tags: percona_mysql_manage_security

- name: create context mapping for non-standard percona_mysql_port (if the port is not already listening)
  command:
    semanage port -a -t mysqld_port_t -p tcp {{ percona_mysql_port.value }}
  when: ansible_os_family == 'RedHat' and {{ percona_mysql_port.value }} != 3306 and percona_mysql_port_check.failed
  tags: percona_mysql_manage_security

- name: copy my.cnf
  template:
    src="my.cnf.j2"
    dest=/etc/mysql/my.cnf
    owner=mysql
    group=mysql
    mode=0640
    seuser=system_u
    serole=object_r
    setype=mysqld_etc_t
    selevel=s0
  notify:
    - restart mysql
    - Update percona_mysql_general_variables
    - Update percona_mysql_percona_general_variables
    - Update percona_mysql_connection_variables
    - Update percona_mysql_threadpooling_variables
    - Update percona_mysql_cache_variables
    - Update percona_mysql_innodb_variables
    - Update percona_mysql_replication_variables
    - Update percona_mysql_logging_variables
    - Update percona_mysql_percona_logging_variables

- name: check if we're installing or upgrading (default is install)
  set_fact:
    percona_mysql_state='latest'
  when: percona_mysql_upgrade
