---
- name: include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: include general mysql configuration options
  include_vars: "{{ item }}.yml"
  with_items:
    - cnf_general
    - cnf_connectivity
    - cnf_cache
    - cnf_innodb
    - cnf_replication
    - cnf_logging

- name: include percona specific options
  include_vars: cnf_percona.yml

- name: include tokudb configuration options
  include_vars: cnf_tokudb.yml

- name: include percona threadpooling configuration options
  include_vars: cnf_threadpool.yml

- name: include ssl configuration options
  include_vars: cnf_ssl.yml

- name: include percona audit logging options
  include_vars: cnf_audit.yml

- name: include numa options
  include_vars: cnf_numa.yml